First proper version
commands, pre, post, and override.

diff --git a/vantage b/vantage
--- a/vantage
+++ b/vantage
@@ -2,7 +2,65 @@
 set -eo pipefail
 shopt -s nullglob
 
-export PLUGIN_PATH=${PLUGIN_PATH:="/usr/local/vantage/plugins"}
+export VG_PLUGIN_PATH=/usr/local/vantage/plugins:"$VG_PLUGIN_PATH"
+export VG_NOT_IMPLEMENTED_EXIT=10
+export VG_VALID_EXIT=0
+
+function find_and_run {
+    paths=$(echo "$VG_PLUGIN_PATH" | tr ':' '\n')
+    implemented=0
+    
+    for path in $paths; do
+        for script in "$path"/*/override; do
+            set +e; $script "$@"; exit_code=$?; set -e
+            if [[ "$exit_code" -eq "$VG_NOT_IMPLEMENTED_EXIT" ]]; then
+                continue
+            fi
+            implemented=1
+            if [ -z ${VG_OVERRIDE_CONTINUE+x} ]; then exit $exit_code; fi
+        done
+    done
+    for path in $paths; do
+        for script in "$path"/*/pre; do
+            set +e; $script "$@"; set -e
+            if [[ "$exit_code" -eq "$VG_NOT_IMPLEMENTED_EXIT" ]]; then
+                continue
+            fi
+            implemented=1
+            if [[ "$exit_code" -ne "$VG_VALID_EXIT" ]]; then
+                exit $exit_code
+            fi
+        done
+    done
+    for path in $paths; do
+        for script in "$path"/*/commands; do
+            set +e; $script "$@"; exit_code=$?; set -e
+            if [[ "$exit_code" -eq "$VG_NOT_IMPLEMENTED_EXIT" ]]; then
+                continue
+            fi
+            implemented=1
+            if [[ "$exit_code" -ne "$VG_VALID_EXIT" ]]; then
+                exit $exit_code
+            fi
+        done
+    done
+    for path in $paths; do
+        for script in "$path"/*/post; do
+            set +e; $script "$@"; set -e
+            if [[ "$exit_code" -eq "$VG_NOT_IMPLEMENTED_EXIT" ]]; then
+                continue
+            fi
+            implemented=1
+            if [[ "$exit_code" -ne "$VG_VALID_EXIT" ]]; then
+                exit $exit_code
+            fi
+        done
+    done
+    if [[ "$implemented" -eq 0 ]]; then
+        echo "Command not found"
+        exit 1
+    fi
+}
 
 case "$1" in
     update)
@@ -13,13 +71,14 @@ case "$1" in
         exit 0
         ;;
     help|'')
-        echo "Usage: vantage [--env ENV_FILE [...]] COMMAND [OPTIONS]"
+        echo "Usage: vantage COMMAND [OPTIONS]"
         echo ""
         echo "Commands:"
-        cat<<EOF | pluginhook commands help | sort
-    help - Print the list of commands
-    update - Update vantage using git
-EOF
-        exit 0
+        echo "    help - Print the list of commands"
+        echo "    update - Update vantage using git"
+        export VG_OVERRIDE_CONTINUE=1
+        find_and_run $@
         ;;
+    *)
+        find_and_run $@
 esac
